name = "rtgo_client"
target = "javascript"
version = "0.0.1"

[dependencies]
gleam_stdlib = "== 0.67.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
lustre = ">= 5.5.2 and < 6.0.0"
rsvp = ">= 1.2.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"

[tools.lustre.html]
links = [
  { rel = "icon", href = "/favicon.svg", type = "image/svg+xml" }
]
